### ISSUE TITLE
TypeError: embedded.forEach is not a function

### ISSUE THREAD

**Issue by voodooattack** [stemey/mongoose-schema#2]
I get the following error when I try to generate a JSON schema like so:

```
  let generator = new JsonSchemaGenerator();
  let jsonSchema = generator.generate(schema);
```

This error occurs:

```
/home/voodooattack/dev/feenda/node_modules/mongoose-schema/JsonSchemaGenerator.js:151
        embedded.forEach(function (path) {
                 ^
    
    TypeError: embedded.forEach is not a function
        at [object Object].JsonSchemaGenerator.generateEmbedded (/home/voodooattack/dev/feenda/node_modules/mongoose-schema/JsonSchemaGenerator.js:151:14)
        at [object Object].JsonSchemaGenerator.generateProperty (/home/voodooattack/dev/feenda/node_modules/mongoose-schema/JsonSchemaGenerator.js:46:36)
        at [object Object].<anonymous> (/home/voodooattack/dev/feenda/node_modules/mongoose-schema/JsonSchemaGenerator.js:61:33)
        at Array.forEach (native)
        at [object Object].JsonSchemaGenerator.generateProperties (/home/voodooattack/dev/feenda/node_modules/mongoose-schema/JsonSchemaGenerator.js:58:31)
        at [object Object].JsonSchemaGenerator.generate (/home/voodooattack/dev/feenda/node_modules/mongoose-schema/JsonSchemaGenerator.js:20:34)
```

**Comment by stemey** [comment]
Please provide your schema. I will check.

**Comment by voodooattack** [comment]
```
import NestedSet from 'mongoose-nested-set';
import mongoose from 'mongoose';
import acl from 'mongoose-acl';

import trackable from './plugins/trackable';
import slug from './plugins/slug';

let schema = new mongoose.Schema({
  views: { type: Number, default: 0 },
  name: { type: String, required: true },
  description: String,
  //establishments: [{ type: mongoose.Schema.ObjectId, ref: 'Establishment' }],
  lastModified: { type: Date, default: Date.now },
  dateCreated: { type: Date, default: Date.now }
}, { strict: true });

schema.plugin(trackable);
schema.plugin(slug);
schema.plugin(NestedSet);
schema.plugin(acl.object);

export default mongoose.model('Category', schema);
```

It appears to only occur when NestedSet is in use.

A new error occurs when NestedSet is commented out and ACL is active:

```
    /home/voodooattack/dev/feenda/node_modules/mongoose-schema/AbstractSchemaGenerator.js:57
        } else if (type.type) {
                       ^
    
    TypeError: Cannot read property 'type' of undefined
        at [object Object].AbstractSchemaGenerator.swaggerTypeFor (/home/voodooattack/dev/feenda/node_modules/mongoose-schema/AbstractSchemaGenerator.js:57:20)
        at [object Object].JsonSchemaGenerator.generateProperty (/home/voodooattack/dev/feenda/node_modules/mongoose-schema/JsonSchemaGenerator.js:44:36)
        at [object Object].<anonymous> (/home/voodooattack/dev/feenda/node_modules/mongoose-schema/JsonSchemaGenerator.js:61:33)
        at Array.forEach (native)
        at [object Object].JsonSchemaGenerator.generateProperties (/home/voodooattack/dev/feenda/node_modules/mongoose-schema/JsonSchemaGenerator.js:58:31)
        at [object Object].JsonSchemaGenerator.generate (/home/voodooattack/dev/feenda/node_modules/mongoose-schema/JsonSchemaGenerator.js:20:34)
```

**Comment by stemey** [comment]
I pushed the branch acl_nested_set#2. It has a fix for the acl plugin. It will ignore the generated proeprty _acl because it is a Mixed or something which is currently not supported. I also added a test that passes for now.

The NestedSet plugin generates a schema that is recognized as an embedded property although it seems it is a parentId property of type ObjectId. I won't investigate further. 

If you need this feature you are welcome to extend the AbstractSchemaGenerator. You probably want to start by extending the convertType method which maps the options.type in the mongoose schema to a converter name. There is a converter method for each of those called "generate"+name (e.g. generateEmbedded()). The implementation of the method should be in the JsonSchemaGenerator.

**Comment by voodooattack** [comment]
Thanks! I will look into it.
